/*
Notebook Navigator - Plugin for Obsidian
Copyright (c) 2025 Johan Sanneblad

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

=========================================================================
GENERATED FILE - DO NOT EDIT src/constants/notebookNavigatorIcon.ts
=========================================================================

Edit the SVG source instead: icon.svg
Generated by: scripts/build-icons.mjs
*/

// Icon identifier used with Obsidian's addIcon()/setIcon()
export const NOTEBOOK_NAVIGATOR_ICON_ID = 'notebook-navigator';

// Full SVG content passed to addIcon() (Obsidian expects viewBox="0 0 100 100")
export const NOTEBOOK_NAVIGATOR_ICON_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100" fill="none" stroke="currentColor">
  <g stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round">
    <rect x="19.88" y="12.42" width="66.42" height="75.21" rx="6.25" stroke-width="8"/>
    <g>
      <line x1="13.29" y1="24.38" x2="26.83" y2="24.38"/><circle cx="26.83" cy="24.38" r="1.38"/>
      <line x1="13.29" y1="37.21" x2="26.83" y2="37.21"/><circle cx="26.83" cy="37.21" r="1.38"/>
      <line x1="13.29" y1="50" x2="26.83" y2="50"/><circle cx="26.83" cy="50" r="1.38"/>
      <line x1="13.29" y1="62.79" x2="26.83" y2="62.79"/><circle cx="26.83" cy="62.79" r="1.38"/>
      <line x1="13.29" y1="75.63" x2="26.83" y2="75.63"/><circle cx="26.83" cy="75.63" r="1.38"/>
    </g>
    <g>
      <circle cx="53.08" cy="50" r="12.63" stroke-width="3"/>
      <polygon points="53.08 37.13 50.38 37.13 51.73 34.79 53.08 32.42 54.44 34.79 55.79 37.13 53.08 37.13"/>
      <polygon points="40.21 50 40.21 52.71 38.04 51.33 35.5 50 38.04 48.67 40.21 47.29 40.21 50"/>
      <polygon points="53.08 62.88 55.79 62.88 54.44 65.21 53.08 67.58 51.73 65.21 50.38 62.88 53.08 62.88"/>
      <polygon points="65.96 50 65.96 47.29 68.29 48.67 70.67 50 68.29 51.33 65.96 52.71 65.96 50"/>
      <polygon points="51.54 51.33 44.92 49.63 58.46 43.67 53.33 57.75 51.54 51.33" fill="currentColor" stroke="none"/>
    </g>
  </g>
</svg>`;
