/*
 * Notebook Navigator - Plugin for Obsidian
 * Copyright (c) 2025 Johan Sanneblad
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const filename = fileURLToPath(import.meta.url);
const dirname = path.dirname(filename);

const projectRoot = path.resolve(dirname, '..');
const sourceSvgPath = path.join(projectRoot, 'icon.svg');
const outputTsPath = path.join(projectRoot, 'src', 'constants', 'notebookNavigatorIcon.ts');

function normalizeNewlines(input) {
    return input.replaceAll('\r\n', '\n').replaceAll('\r', '\n');
}

function escapeTemplateLiteral(input) {
    return input.replaceAll('`', '\\`').replaceAll('${', '\\${');
}

// Pass full SVG to addIcon (like obsidian-to-notion does)
// Obsidian expects viewBox="0 0 100 100" for custom icons
const svgSource = await fs.readFile(sourceSvgPath, 'utf8');
const normalizedSvg = normalizeNewlines(svgSource).trim();
const escapedSvgContent = escapeTemplateLiteral(normalizedSvg);

const header = [
    '/*',
    'Notebook Navigator - Plugin for Obsidian',
    'Copyright (c) 2025 Johan Sanneblad',
    '',
    'This program is free software: you can redistribute it and/or modify',
    'it under the terms of the GNU General Public License as published by',
    'the Free Software Foundation, either version 3 of the License, or',
    '(at your option) any later version.',
    '',
    'This program is distributed in the hope that it will be useful,',
    'but WITHOUT ANY WARRANTY; without even the implied warranty of',
    'MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the',
    'GNU General Public License for more details.',
    '',
    'You should have received a copy of the GNU General Public License',
    'along with this program.  If not, see <https://www.gnu.org/licenses/>.',
    '',
    '=========================================================================',
    `GENERATED FILE - DO NOT EDIT ${path.relative(projectRoot, outputTsPath).split(path.sep).join(path.posix.sep)}`,
    '=========================================================================',
    '',
    `Edit the SVG source instead: ${path.relative(projectRoot, sourceSvgPath).split(path.sep).join(path.posix.sep)}`,
    'Generated by: scripts/build-icons.mjs',
    '*/',
    ''
].join('\n');

const output = `${header}
// Icon identifier used with Obsidian's addIcon()/setIcon()
export const NOTEBOOK_NAVIGATOR_ICON_ID = 'notebook-navigator';

// Full SVG content passed to addIcon() (Obsidian expects viewBox="0 0 100 100")
export const NOTEBOOK_NAVIGATOR_ICON_SVG = \`${escapedSvgContent}\`;
`;

let existing = null;
try {
    existing = await fs.readFile(outputTsPath, 'utf8');
} catch {
    // Generated file may not exist yet
}

if (existing !== output) {
    await fs.writeFile(outputTsPath, output, 'utf8');
}

console.log(`Built ${path.relative(projectRoot, outputTsPath)}`);
